export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILURE = 'GET_FILTERS_FAILURE';

export const GET_LANGUAGE_SUCCESS = 'GET_LANGUAGE_SUCCESS';
export const GET_LANGUAGE_FAILURE = 'GET_LANGUAGE_FAILURE';

export const GET_PLAYGROUNDS_SUCCESS = 'GET_PLAYGROUNDS_SUCCESS';
export const GET_PLAYGROUNDS_FAILURE = 'GET_PLAYGROUNDS_FAILURE';

export const GET_CLASS_SNIPPET_SUCCESS = 'GET_CLASS_SNIPPET_SUCCESS';
export const GET_CLASS_SNIPPET_FAILURE = 'GET_CLASS_SNIPPET_FAILURE';

export const GET_CLASS_EXP_SUCCESS = 'GET_CLASS_EXP_SUCCESS';
export const GET_CLASS_EXP_FAILURE = 'GET_CLASS_EXP_FAILURE';

export const GET_FUNCTION_SNIPPET_SUCCESS = 'GET_FUNCTION_SNIPPET_SUCCESS';
export const GET_FUNCTION_SNIPPET_FAILURE = 'GET_FUNCTION_SNIPPET_FAILURE';

export const GET_FUNCTION_EXP_SUCCESS = 'GET_FUNCTION_EXP_SUCCESS';
export const GET_FUNCTION_EXP_FAILURE = 'GET_FUNCTION_EXP_FAILURE';

export const GET_VARIABLE_SNIPPET_SUCCESS = 'GET_VARIABLE_SNIPPET_SUCCESS';
export const GET_VARIABLE_SNIPPET_FAILURE = 'GET_VARIABLE_SNIPPET_FAILURE';

export const GET_VARIABLE_EXP_SUCCESS = 'GET_VARIABLE_EXP_SUCCESS';
export const GET_VARIABLE_EXP_FAILURE = 'GET_VARIABLE_EXP_FAILURE';
