import React from 'react';
import './terms-of-use.scss';

export const TermsOfUse = () => {
	return (
		<div className="terms-section pt-6">
			<div className="container">
				<div className="terms-title">
					<h2>Terms of Use</h2>
					<p>Last Updated: December 2024</p>
				</div>
				<div className="row">
					<h3>
						<u>Definitions</u>
					</h3>
					<p>For the purposes of this Privacy Policy:</p>
					<ul>
						<li>
							<b>Account</b> means a unique account created for You to access our
							Service or parts of our Service.
						</li>
						<li>
							<b>Company</b> (referred to as either "the Company", "We", "Us" or "Our"
							in this Agreement) refers to Code Insight.
						</li>
						<li>
							<b>Cookies</b> are small files that are placed on Your computer, mobile
							device or any other device by a website, containing the details of Your
							browsing history on that website among its many uses.
						</li>
						<li>
							<b>Country</b> refers to: Louisiana, United States
						</li>
						<li>
							<b>Device</b> means any device that can access the Service such as a
							computer, a cellphone or a digital tablet.
						</li>
						<li>
							<b>Personal Data</b> is any information that relates to an identified or
							identifiable individual.
						</li>
						<li>
							<b>Service</b> refers to the Website.
						</li>
						<li>
							<b>Service Provider</b> means any natural or legal person who processes
							the data on behalf of the Company. It refers to third-party companies or
							individuals employed by the Company to facilitate the Service, to
							provide the Service on behalf of the Company, to perform services
							related to the Service or to assist the Company in analyzing how the
							Service is used.
						</li>
						<li>
							<b>Third-party Social Media Service</b> refers to any website or any
							social network website through which a User can log in or create an
							account to use the Service.
						</li>
						<li>
							<b>Usage Data</b> refers to data collected automatically, either
							generated by the use of the Service or from the Service infrastructure
							itself (for example, the duration of a page visit).
						</li>
						<li>
							<b>Website</b> refers to Code Insight, accessible from{' '}
							<a href="/">https://www.codeinsight.com</a>
						</li>
						<li>
							<b>You</b> means the individual accessing or using the Service, or the
							company, or other legal entity on behalf of which such individual is
							accessing or using the Service, as applicable.
						</li>
					</ul>
				</div>
				<div className="row">
					<h3>
						<u>Collecting and Using Your Personal Data</u>
					</h3>
					<h4>1. Usage Data</h4>
					<p>Usage Data is collected automatically when using the Service.</p>
					<p>
						Usage Data may include information such as Your Device's Internet Protocol
						address (e.g. IP address), browser type, browser version, the pages of our
						Service that You visit, the time and date of Your visit, the time spent on
						those pages, unique device identifiers and other diagnostic data.
					</p>
					<p>
						When You access the Service by or through a mobile device, We may collect
						certain information automatically, including, but not limited to, the type
						of mobile device You use, Your mobile device unique ID, the IP address of
						Your mobile device, Your mobile operating system, the type of mobile
						Internet browser You use, unique device identifiers and other diagnostic
						data.
					</p>
					<p>
						We may also collect information that Your browser sends whenever You visit
						our Service or when You access the Service by or through a mobile device.
					</p>
					<h4>2. Tracking Technologies and Cookies</h4>
					<p>
						We use Cookies and similar tracking technologies to track the activity on
						Our Service and store certain information. Tracking technologies used are
						beacons, tags, and scripts to collect and track information and to improve
						and analyze Our Service. The technologies We use may include:
					</p>
					<ul>
						<li>
							<b>Cookies or Browser Cookies</b>. A cookie is a small file placed on
							Your Device. You can instruct Your browser to refuse all Cookies or to
							indicate when a Cookie is being sent. However, if You do not accept
							Cookies, You may not be able to use some parts of our Service. Unless
							you have adjusted Your browser setting so that it will refuse Cookies,
							our Service may use Cookies.
						</li>
						<li>
							<b>Flash Cookies</b>. Certain features of our Service may use local
							stored objects (or Flash Cookies) to collect and store information about
							Your preferences or Your activity on our Service. Flash Cookies are not
							managed by the same browser settings as those used for Browser Cookies.
						</li>
						<li>
							<b>Web Beacons</b>. Certain sections of our Service and our emails may
							contain small electronic files known as web beacons (also referred to as
							clear gifs, pixel tags, and single-pixel gifs) that permit the Company,
							for example, to count users who have visited those pages or opened an
							email and for other related website statistics (for example, recording
							the popularity of a certain section and verifying system and server
							integrity).
						</li>
					</ul>
					<p>
						Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain
						on Your personal computer or mobile device when You go offline, while
						Session Cookies are deleted as soon as You close Your web browser. You can
						learn more about cookies here: Cookies by TermsFeed Generator.
					</p>
					<p>
						We use both Session and Persistent Cookies for the purposes set out below:
					</p>
					<ul>
						<li>
							<b>Necessary / Essential Cookies</b>
							<p>Type: Session Cookies</p>
							<p>Administered by: Us</p>
							<p>
								Purpose: These Cookies are essential to provide You with services
								available through the Website and to enable You to use some of its
								features. They help to authenticate users and prevent fraudulent use
								of user accounts. Without these Cookies, the services that You have
								asked for cannot be provided, and We only use these Cookies to
								provide You with those services.
							</p>
						</li>
						<li>
							<b>Cookies Policy / Notice Acceptance Cookies</b>
							<p>Type: Persistent Cookies</p>
							<p>Administered by: Us</p>
							<p>
								Purpose: These Cookies identify if users have accepted the use of
								cookies on the Website.
							</p>
						</li>
						<li>
							<b>Functionality Cookies</b>
							<p>Type: Persistent Cookies</p>
							<p>Administered by: Us</p>
							<p>
								Purpose: These Cookies allow us to remember choices You make when
								You use the Website, such as remembering your login details or
								language preference. The purpose of these Cookies is to provide You
								with a more personal experience and to avoid You having to re-enter
								your preferences every time You use the Website.
							</p>
						</li>
					</ul>
					<p>
						For more information about the cookies we use and your choices regarding
						cookies, please visit our Cookies Policy or the Cookies section of our
						Privacy Policy.
					</p>
				</div>
			</div>
		</div>
	);
};
